<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="hedge-fund.aspx.cs" Inherits="dailypunch.hedge_fund" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">

    <style>
      .back-img{
          padding-top: 100px;
          
          padding-bottom: 100px;
          width: 1883.5px;
          background-image: url('imgs/hedge_fund.png');
          background-attachment: fixed;
          background-repeat: no-repeat;
          background-size: cover;
          background-position: center;
      }
     .h1{
         font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;
         font-size: 40px;
         font-weight: bold;
         color: #088F8F;
         vertical-align: baseline;
     }
     .h2{
         padding-top: 7px;
         font-size: 25px;
         color: #03396C;
         margin-bottom: 5px;
            
        }
     .gap{
         height: 30px;
     }
</style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">

    <div class="back-img">

        <div style="width: 1093px; margin-left: 500px;">
            <div class="h1">
                What is a hedge fund?
            </div>
            <div class="h2">
                A hedge fund is an investment fund that trades in relatively liquid assets and is able to make extensive use of more complex trading, portfolio-construction and risk management techniques to improve performance, such as short selling, leverage and derivatives.
            </div>
            <div class="gap"></div>
            <div class="h1">Types of hedge funds:</div>
            <div class="h2"><b>Domestic hedge funds:</b> Domestic hedge funds are open to only those investors that are subject to the origin&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;country’s taxation.</div>
            <div class="h2"><b>Offshore hedge funds:</b> An offshore hedge fund is established outside of your own country, preferably in a &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; low taxation country.</div>
            <div class="h2"><b>Fund of funds:</b> Fund of funds are basically mutual funds that invest in other hedge mutual funds rather than &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;the individual underlying securities.</div>&nbsp;
            <div class="gap"></div>
            <div class="h1">Types of hedge fund strategies:</div>
            <div class="h2"><b>Event driven:</b>&nbsp;There are few event driven hedge mutual funds that invest to take advantage of price<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;movements generated by corporate events. For example: merger arbitrage funds and&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp;distressed asset funds.</div>
            <div class="h2"><b>Market neutral:</b>&nbsp;There are also some market neutral funds that seek to minimize&nbsp;market risks. This&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;category included convertible bonds, short and long equity funds and fixed income&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp; arbitrage.</div>
            <div class="h2" style="border: thin solid #000080"><b style="text-decoration: underline">Long/Short selling:</b> By definition, short-selling means that you sell a security without actually buying it&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;but with the notion of buying it at a predetermined future date and price. You hope&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;for the share price to drop on this predetermined future date and book profits.</div>
            <div class="h2"><b>Arbitrage:</b> An arbitrage-oriented strategy means buying a security in one market where the security is&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; trading at a lower price and then selling the same security at a higher price in another market&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp;to book some profit. This can also be used for buying and selling two very highly correlated &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;securities simultaneously to book profit when markets are moving sideways. This is called&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;relative value arbitrage. Both the securities could be from one asset class or multiple ones.</div>
            <div class="h2"><b>Market-driven:</b> Hedge mutual funds also take advantage of global market trends before they make the&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;decision to invest in&nbsp;securities. They look at global macros and how they will impact&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;interest rates, equities, commodities and&nbsp;currencies</div>
        </div>
    </div>
    <div>
            <footer style="background-color: #2a4d69; height: 419px; width: 1883px;">
                <div style="height: 420px; margin-left: 28px">
                    <div style="color: #e7eff6; font-size: 25px; letter-spacing: 0.3em; font-weight: 600; text-align: left; height: 194px; margin-top: 0px;">
                        For any inquiries,<br>
                        please email us:<br>
                        <br>
                        <div style="font-size: 20px"><a href="mailto:info@dailypunch.com" style="text-decoration: none; color: #e7eff6; text-shadow: 5px 5px 8px rgb(0 0 0);">info@dailypunch.com</a></div>
                    </div>
                    <div style="color: #e7eff6; font-size: 20px; font-weight: 300; text-align: left; height: 34px;">© 2023 by DailyPunch Hedge Fund.-All Rights Reserved.</div>
                </div>
            </footer>
        </div>
</asp:Content>
